name: Build Github pages

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master


jobs:
  builddocs:
    name: Build Documenation files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup python3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Merge Old docs
      run: |
        git fetch origin  +refs/heads/gh-pages:refs/remotes/origin/gh-pages
        git merge -s ours origin/gh-pages
        git checkout -b gh-pages
    - name: Install docutils
      run: |
            python -m pip install --upgrade pip
            pip install docutils
            cd $GITHUB_WORKSPACE/docs
            for file in *.rst; do rst2html.py $file >  ${file%%rst}html; done
            git add .
            git commit -m 'Rebuild HTML for gh-pages'
            git push
