name: Python Unittests

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master


jobs:
  python_matrix:
    strategy:
        matrix:
            version: ['3.7', '3.8', '3.9', '3.10', '3.11']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set git identity
      run: |
        git config --global user.email "testrunner@github.local"
        git config --global user.name "Test Runner"
    - name: Run tests
      run: |
        cd $GITHUB_WORKSPACE
        python -m unittest discover -p '*.py' -s tests
